version: "3"
services:
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=helloworld
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017